DROP TABLE dim_categoria CASCADE CONSTRAINTS;

DROP TABLE dim_centro_distribuicao CASCADE CONSTRAINTS;

DROP TABLE dim_fornecedor CASCADE CONSTRAINTS;

DROP TABLE dim_produto CASCADE CONSTRAINTS;

DROP TABLE dim_tempo CASCADE CONSTRAINTS;

DROP TABLE fto_estoque CASCADE CONSTRAINTS;
